#define BLYNK_TEMPLATE_ID "TMPL6LSpSI8y9"
#define BLYNK_TEMPLATE_NAME "Gas Leakage Alert"
#define BLYNK_AUTH_TOKEN "6zS72-C0p5Nt52I5FqLR4VSr6CLj3Cag"

//above one is generated by Blynk

#define BLYNK_PRINT Serial
#include <ESP8266WiFi.h>
#include <BlynkSimpleEsp8266.h>

char auth[] = BLYNK_AUTH_TOKEN;
char ssid[] = "Wifi Username";
char pass[] = "Wifi Password";

int smokeA0 = A0;
int data = 0;

BlynkTimer timer;

// Define pins
#define MQ2_SENSOR A0  
#define LED_PIN D0     

int gasThreshold = 105;  // Threshold for gas detection


void sendSensor(){
  int data = analogRead(smokeA0);  // Read the gas value from the MQ2 sensor
  Blynk.virtualWrite(V0, data);    // Send the gas value to the Blynk app (Virtual Pin 0)
  
  Serial.print("Pin A0: ");
  Serial.println(data);

  if (data > gasThreshold) {       // Check if the gas value exceeds the threshold
    digitalWrite(LED_PIN, HIGH);   // Turn on the LED
    Blynk.logEvent("gas_alert", "Gas Leakage Detected");
  } else {
    digitalWrite(LED_PIN, LOW);    // Turn off the LED
  }
}

void setup() {
  Serial.begin(115200);
  Blynk.begin(auth, ssid, pass);

  // Set up pin modes
  pinMode(smokeA0, INPUT);
  pinMode(LED_PIN, OUTPUT);

  timer.setInterval(2500L, sendSensor);  // Call sendSensor() every 2.5 seconds
}

void loop() {
  Blynk.run();   // Run Blynk
  timer.run();   // Run the timer
}